### ISSUE TITLE
Bouncer can't connect to CrowdSec instance

### ISSUE THREAD

**Issue by SAOPP** [fbonalair/traefik-crowdsec-bouncer#24]
Hi!

Face with strange behaviour, I have an several same install of crowdsec and traefik bouncer in docker, and right now I install this stuff to my vps, but, not understand what is wrong, maybe someone can help and resolve it, traefik bouncer can't connect to the crowdsec instance, 'coz ip address of container in not in bouncers list, and I can't understand whats is wrong in my compose or my settings of current stack.

Here is an screen of bouncers list:
![image](https://user-images.githubusercontent.com/5647009/163139500-03b35b9b-3659-4f26-8fdb-e0bf5cd04c92.png)

Here is an my containers:
![image](https://user-images.githubusercontent.com/5647009/163139864-fbf440a5-7e37-4cc2-998a-b47c42fe4dc8.png)

And my stack:

```
version: '3'

networks:
  proxy:
    external: true

volumes:
  config:
    driver: local
  db:
    driver: local

services:

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    networks:
      - proxy
    environment:
      - TZ=Europe/Kiev
      - COLLECTIONS="crowdsecurity/linux crowdsecurity/traefik"
      - GID=${GID-1000}
    volumes:
      - ${DOCKER_HOST_PATH}/crowdsec/config/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ${DOCKER_HOST_PATH}/crowdsec/config/profiles.yaml:/etc/crowdsec/profiles.yaml
      - ${DOCKER_HOST_PATH}/crowdsec/notifications/http.yaml:/etc/crowdsec/notifications/http.yaml
      - db:/var/lib/crowdsec/data/
      - config:/etc/crowdsec/
      # Traefik's logs read-only
      - ${DOCKER_HOST_PATH}/traefik/logs:/var/log/traefik:ro
      # Authelia's logs read-only
      #- ${DOCKER_HOST_PATH}/authelia/authelia.log:/var/log/authelia.log:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "35m"
      
  traefik-crowdsec-bouncer:
    image: docker.io/fbonalair/traefik-crowdsec-bouncer:latest
    container_name: traefik-crowdsec-bouncer
    networks:
      - proxy
    depends_on:
      - crowdsec
    environment:
      - TZ=Europe/Kiev
      - CROWDSEC_BOUNCER_API_KEY=${BOUNCER_TRAEFIK_API_KEY}
      - CROWDSEC_AGENT_HOST=crowdsec:8080
      - CROWDSEC_BOUNCER_LOG_LEVEL=0
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
```
The only difference from my previous stacks: I added telegram alerts, and my internal docker network is `192.168.135.0/24` - and that's all differents.

**Comment by SAOPP** [comment]
I tried different scenarios, specified the IP address of CrowdSec container, added another container from the default docker subnet, I don’t understand what the problem is and why the CrowdSec behaves like this.

**Comment by tinolin** [comment]
As I have it with SWARM, I have this variable: "CROWDSEC_AGENT_HOST=192.168.135.8:8080" in the definition of the service "traefik-crowdsec-bouncer" in this way, since it must be explicit, because of how swarm makes the names of The containers

**Comment by SAOPP** [comment]
But, I don’t have a swarm, and this option didn't work for me, I tried to add the address of the container natively. :(

**Comment by SAOPP** [comment]
Damn it, I tried all possible options, I just broke my head, I don’t understand where to dig, nonsense. :disappointed:

**Comment by SAOPP** [comment]
Is there any chance to get more debug logs from the bouncer?

**Comment by tinolin** [comment]
jaja take it easy my friend!! what docker command do you run? can you telnet to the port?

I leave my configuration for you to try:

```
version: "3.8"

services:
  crowd_sec:
    container_name: "crowdsec-example"
    image: crowdsecurity/crowdsec:v1.3.2    
    environment:
      - GID="${GID-1000}"
      - COLLECTIONS="crowdsecurity/linux crowdsecurity/traefik"    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro    
      - /mnt/data/docker/crowdsec/config/acquis.yaml:/etc/crowdsec/acquis.yaml
      - /mnt/data/docker/traefik-logs/:/var/log/traefik/:ro
      - /var/log/auth.log:/var/log/auth.log:ro
      - crowdsec_db:/var/lib/crowdsec/data/
      - crowdsec_config:/etc/crowdsec/
    ports:
     - target: 8080
       published: 8085
       protocol: tcp
       mode: host
     - target: 6060
       published: 8086
       protocol: tcp
       mode: host         
    restart: unless-stopped
    networks:
      - traefik-public

  bouncer:
    image: fbonalair/traefik-crowdsec-bouncer:latest
    container_name: "bouncer"
    environment:
      - CROWDSEC_BOUNCER_API_KEY=
      - CROWDSEC_AGENT_HOST=192.168.135.8:8085
      - PORT=8084
      - GIN_MODE=release
    restart: unless-stopped
    ports:
     - target: 8084
       published: 3303
       protocol: tcp
       mode: host    
    networks:
      - traefik-public      
    depends_on:
      - 'crowdsec-example'
      - crowd_sec
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.bouncer.rule=Host(`bouncer.example.com`)
        - traefik.http.services.bouncer.loadbalancer.server.port=8084
        - traefik.http.routers.bouncer.tls.certresolver=letsencryptresolver
        - traefik.http.routers.bouncer.tls=true
        - traefik.http.routers.bouncer.entrypoints=websecure
        #- traefik.http.routers.bouncer.middlewares=middlewares-secure-headers@file    


networks:
  traefik-public:
      external: true

volumes:
        crowdsec_db:
                driver: local
                driver_opts:
                        type: volume
                        o: bind
                        device: /mnt/data/docker/crowdsec/db
        crowdsec_config:
                driver: local
                driver_opts:
                        type: volume
                        o: bind
                        device: /mnt/data/docker/crowdsec/config
        traefik-logs:
                external: true
# mkdir -p /mnt/data/docker/crowdsec/{config,db,data}
# touch /mnt/data/docker/crowdsec/config/acquis.yaml 
```   
you can try on host:

```
root@myhost:~# telnet 192.168.135.8 8085
Trying 192.168.135.8...
Connected to 192.168.135.8.
Escape character is '^]'.
```

what does the console show you?
