### ISSUE TITLE
Under load, bouncer bans legitimate traffic

### ISSUE THREAD

**Issue by Vertiwell** [fbonalair/traefik-crowdsec-bouncer#30]
Hi,
When under heavy load requests are forbidden:
traefik-bouncer-8567488c8-jckp2 traefik-bouncer 2022-08-18T11:22:49.158912821+10:00 2022-08-18T01:22:49Z WRN An error occurred while checking IP "" error="Get \"http://crowdsec-service.crowdsec.svc.cluster.local:8080/v1/decisions?type=ban&ip=10.42.8.192\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Is it possible to introduce an environment variable to increase this timeout (until the initial load issues can be sorted)
Cheers.

**Comment by fbonalair** [comment]
Hello,

Yeah sure. It should be quite straightforward to implement in the [Healthchecker](https://github.com/fbonalair/traefik-crowdsec-bouncer/blob/main/healthcheck/healthchecker.go) with go [http client timeout property](https://pkg.go.dev/net/http#Client).

**Comment by Vertiwell** [comment]
I would really appreciate that as this is currently preventing me from running Crowdsec in our test environment (we have limited hardware), so it's production or bust!

**Comment by fbonalair** [comment]
The feature is now available in container version v0.5.0

**Comment by Vertiwell** [comment]
Awesome, thank you!
How can I apply this to the helm chart?
Something like:
```
bouncer:
  crowdsec_bouncer_api_key: $BOUNCERKEY
  crowdsec_agent_host: "crowdsec-service.crowdsec.svc.cluster.local:8080"
  health_checker_timeout_duration: 30s
replicaCount: 3
```

This is what my pod spec looks like:
```
    Image:          fbonalair/traefik-crowdsec-bouncer:0.5.0
    Environment:
      HEALTH_CHECKER_TIMEOUT_DURATION:  30s    
```
Still seem to be getting timeouts, but it may be something else
