### ISSUE TITLE
traefik-bouncer not connecting

### ISSUE THREAD

**Issue by lewisd19** [fbonalair/traefik-crowdsec-bouncer#41]
I am having a strange issue getting the traefik-bouncer up and running. Ive followed the steps and have got it going successfully on two other hosts but for whatever reason the host im attempting to get it going on will not connect to my traefik container. Im not sure what Im missing and super confused.

cscli bouncers list:

`----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Name              IP Address     Valid   Last API pull          Type                        Version                                                        Auth Type
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 blocklistMirror   172.168.90.1   ✔️       2022-11-25T13:20:15Z   crowdsec-blocklist-mirror   v0.0.1-debian-pragmatic-0c8983c08afb28d82d18c4835458aaa0019-   api-key
                                                                                             3fa4f
 traefik-bouncer                  ✔️       2022-11-25T13:15:28Z                                                                                              api-key
----------------------------------------------------------------------------------------------------------------------------------------------------------------------`

logs from traefik-bouncer in debug:

`[GIN-debug] GET    /api/v1/ping              --> github.com/fbonalair/traefik-crowdsec-bouncer/controler.Ping (2 handlers)
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
[GIN-debug] Listening and serving HTTP on :8080
[GIN-debug] Environment variable PORT is undefined. Using port :8080 by default
[GIN-debug] GET    /api/v1/metrics           --> github.com/fbonalair/traefik-crowdsec-bouncer/controler.Metrics (2 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
[GIN-debug] GET    /api/v1/healthz           --> github.com/fbonalair/traefik-crowdsec-bouncer/controler.Healthz (2 handlers)
[GIN-debug] GET    /api/v1/forwardAuth       --> github.com/fbonalair/traefik-crowdsec-bouncer/controler.ForwardAuth (2 handlers)
 - using code:	gin.SetMode(gin.ReleaseMode)
 - using env:	export GIN_MODE=release
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.`

also was getting this error which prompted me to nuke the setup and start over:

`{"level":"warn","error":"invalid character 'p' after top-level value","time":"2022-11-24T01:29:00Z","message":"An error occurred while checking IP """}`

Any ideas? Thanks in advance.

**Comment by jphp3405** [comment]
Hello,

I have the same issue. 

Here is my setup: 

```
  crowdsec:
    <<: *common-keys-core 
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    ports:
      - "8080:8080"
    environment:
      COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/linux baudneo/gotify LePresidente/jellyfin LePresidente/jellyseerr crowdsecurity/mariadb crowdsecurity/nextcloud schiz0phr3ne/prowlarr schiz0phr3ne/radarr schiz0phr3ne/sonarr timokoessler/uptime-kuma Dominic-Wagner/vaultwarden"
      GID: "${GID-1001}"
    volumes:
      - $LOGSDIR:/logs:ro
      - /var/log:/var/log:ro
      - $APPDATADIR/crowdsec/data:/var/lib/crowdsec/data
      - $APPDATADIR/crowdsec/config:/etc/crowdsec

# CrowdSec Bouncer - Traefik
  traefik-bouncer:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    image: fbonalair/traefik-crowdsec-bouncer
    container_name: traefik-bouncer
    expose:
      - 8080
    depends_on:
      - crowdsec
    environment:
      GIN_MODE: release 
      CROWDSEC_BOUNCER_API_KEY : $CROWDSEC_BOUNCER_TRAEFIK_API_KEY 
      CROWDSEC_AGENT_HOST : crowdsec:8080 
```


Have you resolve it ?
