### ISSUE TITLE
No Docker console logs

### ISSUE THREAD

**Issue by modem7** [fbonalair/traefik-crowdsec-bouncer#43]
After spinning up the container, I do not get any output in docker logs. 

![image](https://user-images.githubusercontent.com/4349962/215308313-29c24256-7509-4088-8ab7-835f77ec3770.png)

```yaml
  # CrowdSec Bouncer - Traefik
  traefik-bouncer:
    image: fbonalair/traefik-crowdsec-bouncer
    container_name: Crowdsec-Traefik-Bouncer
    networks:
      pihole:
        ipv4_address: '172.22.0.127'
    environment:
      - GIN_MODE=release # default is debug (more logs)
      - CROWDSEC_BOUNCER_API_KEY=$CROWDSEC_BOUNCER_TRAEFIK_API_KEY # sudo docker exec crowdsec cscli bouncers add traefik-bouncer
      - CROWDSEC_AGENT_HOST=crowdsec:8080 # CrowdSec host and port
      - CROWDSEC_BOUNCER_LOG_LEVEL=2 # 1 INFO 2 WARN https://pkg.go.dev/github.com/rs/zerolog#readme-leveled-logging
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    restart: always
    mem_limit: 200m
    mem_reservation: 50m
    depends_on:
      - crowdsec
```

If I set the GIN_MODE to `debug`, I get logs, but not in `release`.

![image](https://user-images.githubusercontent.com/4349962/215308424-0ae62195-6c30-4411-892e-20a782aaab10.png)
