### ISSUE TITLE
Healthcheck error

### ISSUE THREAD

**Issue by modem7** [fbonalair/traefik-crowdsec-bouncer#56]
Getting the following error in my healthcheck for some reason: 

```console
End 2024-01-25T10:38:01.070081694Z
ExitCode -1
Output unable to find user nonroot: no matching entries in passwd file
Start 2024-01-25T10:38:01.068425321Z
```

```yaml
  # CrowdSec Bouncer - Traefik
  traefik-bouncer:
    image: fbonalair/traefik-crowdsec-bouncer
    container_name: Crowdsec-Traefik-Bouncer
    networks:
      pihole:
        ipv4_address: '172.22.0.127'
    environment:
      - GIN_MODE=debug # default is debug (more logs)
      - CROWDSEC_BOUNCER_API_KEY=$CROWDSEC_BOUNCER_TRAEFIK_API_KEY # sudo docker exec crowdsec cscli bouncers add traefik-bouncer
      - CROWDSEC_AGENT_HOST=crowdsec:8080 # CrowdSec host and port
      - CROWDSEC_BOUNCER_LOG_LEVEL=1 # 1 INFO 2 WARN https://pkg.go.dev/github.com/rs/zerolog#readme-leveled-logging
    labels:
      - "backup"
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    restart: always
    mem_limit: 200m
    mem_reservation: 50m
    depends_on:
      - crowdsec
```
